package user;

import data.*;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 * Contains the components and code necessary to gather the information
 * to be sent to the DbManager to delete the selected row from the 
 * access database.
 * 
 * @author Steven Chavez <schavez256@yahoo.com>
 * File: DeletePanel.java
 * ChavezP8: Database Manipulation
 * CIS 2235
 */
public class DeletePanel extends javax.swing.JPanel {

    private HandTool tool;
    private DbManager db = new DbManager();
    private HandToolFrame frame;
    private JLabel  delete_lblBrand, delete_lblKind, delete_lblSize;
    private JTextField  delete_txtFBrand, delete_txtFKind, delete_txtFSize;
    private JButton delete_btDelete;
   
    public DeletePanel(HandToolFrame frame) 
    {
        this.frame = frame;
        initComponents();
        
        // Initialize JLabels
        delete_lblBrand = new JLabel("Brand");
        delete_lblKind = new JLabel("Kind");
        delete_lblSize = new JLabel("Size");
        
        // Initialize JTextFields
        delete_txtFBrand = new JTextField();
        delete_txtFKind = new JTextField();
        delete_txtFSize = new JTextField();
        
        // Initialize JButton
        delete_btDelete = new JButton("Delete");
        delete_btDelete.setForeground(Color.red);
        
        setLayout(new GridLayout(7,1,10,10));
        
        // add components to layout
        add(delete_lblBrand);
        add(delete_txtFBrand);
        
        add(delete_lblKind);
        add(delete_txtFKind);
        
        add(delete_lblSize);
        add(delete_txtFSize);
        
        add(delete_btDelete);
        
        // Create and register anonymous class listeners
        delete_btDelete.addActionListener(new BtDeleteActionListener());

    }
    
    // fills delete panel components with appropriate data
    public void setDeletePanel(HandTool ht)
    {
        tool = ht;
        delete_txtFBrand.setText(tool.getBrand());
        delete_txtFKind.setText(tool.getKind());
        delete_txtFSize.setText(tool.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    //Sends the HandTool object to be deleted to the DbManager when button is
    //clicked.
    private class BtDeleteActionListener implements ActionListener 
    {
        @Override
        public void actionPerformed(ActionEvent e) 
        {
            try 
            {
                db.delete(tool);
                frame.updateList();
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), 
                                "SQL Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
}
