package user;

import data.*;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;


/**
 * Contains the necessary components to gather the information needed to send 
 * to the DbManager so that the selected row can be updated.
 * 
 * @author Steven Chavez <schavez256@yahoo.com>
 * File: UpdatePanel.java
 * ChavezP8: Database Manipulation
 * CIS 2235
 */
public class UpdatePanel extends javax.swing.JPanel {
    
    private HandTool tool;
    private DbManager db = new DbManager();
    private HandToolFrame frame;
    private JLabel  update_lblBrand, update_lblKind, update_lblSize, 
                    update_lblCost, update_lblDate, update_lblWarranty;
    private JTextField  update_txtFBrand, update_txtFKind, update_txtFSize,
                        update_txtFCost, update_txtFDate;
    private JRadioButton update_rbWarranty;
    private JButton update_btUpdate;
   
    
    public UpdatePanel(HandToolFrame frame) 
    {
        this.frame = frame;
        
        initComponents();
        
        // Initialize JLabels
        update_lblBrand = new JLabel("Brand");
        update_lblKind = new JLabel("Kind");
        update_lblSize = new JLabel("Size");
        update_lblCost = new JLabel("Cost");
        update_lblDate = new JLabel("Date (Year-Month-Day)");
        update_lblWarranty = new JLabel("Life Time Warranty?");
        
        // Initialize JTextFields
        update_txtFBrand = new JTextField();
        update_txtFKind = new JTextField();
        update_txtFSize = new JTextField();
        update_txtFCost = new JTextField();
        update_txtFDate = new JTextField();
        
        // Initialize JRadioButton
        update_rbWarranty = new JRadioButton();
        
        // Initialize JButton
        update_btUpdate = new JButton("Update");
        
        setLayout(new GridLayout(7,2,10,10));
        
        // add components to layout
        add(update_lblBrand);
        add(update_txtFBrand);
        
        add(update_lblKind);
        add(update_txtFKind);
        
        add(update_lblSize);
        add(update_txtFSize);
        
        add(update_lblCost);
        add(update_txtFCost);
        
        add(update_lblDate);
        add(update_txtFDate);
        
        add(update_lblWarranty);
        add(update_rbWarranty);
        
        add(update_btUpdate);
        
        // Create and register anonymous class listeners
        update_btUpdate.addActionListener(new BtUpdateActionListener());
    }
    
    public void setUpdatePanel(HandTool ht)
    {
        
        tool = ht;
        update_txtFBrand.setText(tool.getBrand());
        update_txtFKind.setText(tool.getKind());
        update_txtFSize.setText(tool.getSize());
        update_txtFCost.setText(String.format("%.02f", tool.getCost()));
        update_txtFDate.setText(tool.getPurchaseDate());
        update_rbWarranty.setSelected(tool.getWarranty());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private class BtUpdateActionListener implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            tool.setBrand(update_txtFBrand.getText());
            tool.setKind(update_txtFKind.getText());
            tool.setCost(Double.parseDouble(update_txtFCost.getText()));
            tool.setSize(update_txtFSize.getText());
            tool.setPurchaseDate(update_txtFDate.getText());
            tool.setWarranty(update_rbWarranty.isSelected());
            
            try {
                db.update(tool);                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), 
                                "SQL Error",JOptionPane.INFORMATION_MESSAGE);
            }
            
            frame.updateList();
        }
    }
}
