package chavezp6;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * GUI that allows user to encode and decode messages by reading the saved
 * encoded messages. 
 * 
 * @author Steven Chavez <schavez256@yahoo.com>
 * File: EnigmaFrame.java
 * Program 6: Enigma
 * CIS2235
 */
public class EnigmaFrame extends javax.swing.JFrame {

    private Enigma enigma;
    private String encodedMsg;
    private int encodeKey;
    
    
    /**
     * Creates new form EnigmaFrame
     */
    public EnigmaFrame() {
        initComponents();
        
        enigma = new Enigma();
        
        
        //initailize combo box
        for(int i=0; i <50; i++)
        {
            cbxKey.addItem(i+1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtFieldMsg = new javax.swing.JTextField();
        cbxKey = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        rbRandom = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResults = new javax.swing.JTextArea();
        btSave = new javax.swing.JButton();
        btEncode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btOpenFile = new javax.swing.JButton();
        lblEncodedMsg = new javax.swing.JLabel();
        lblEncodeKey = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDecodeMsg = new javax.swing.JTextArea();
        btDecode = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaEncodeMsg = new javax.swing.JTextArea();
        lblEncodedMsg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChavezP6: Enigma");

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enigma Machine");

        btClear.setBackground(new java.awt.Color(255, 0, 0));
        btClear.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        btClear.setForeground(new java.awt.Color(0, 0, 0));
        btClear.setText("Clear");
        btClear.setToolTipText("Clears the form");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jTabbedPane2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        txtFieldMsg.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtFieldMsg.setToolTipText("Enter the message you wish to encode here");

        cbxKey.setToolTipText("Select a value between 1-50");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel2.setText("Key");

        rbRandom.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        rbRandom.setText("Random Key");
        rbRandom.setToolTipText("Generates a random key");

        txtAreaResults.setColumns(20);
        txtAreaResults.setRows(5);
        txtAreaResults.setToolTipText("");
        jScrollPane1.setViewportView(txtAreaResults);

        btSave.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        btSave.setText("Save");
        btSave.setToolTipText("Saves your encoded message and key");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btEncode.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        btEncode.setText("Encode");
        btEncode.setToolTipText("Encodes the message above");
        btEncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel3.setText("Message");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("Encoded Message");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxKey, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btEncode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(txtFieldMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbRandom))
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEncode, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Encode", jPanel2);

        btOpenFile.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        btOpenFile.setText("Open File");
        btOpenFile.setToolTipText("Opens the file you wish to decode");
        btOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenFileActionPerformed(evt);
            }
        });

        lblEncodedMsg.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblEncodedMsg.setText("Encoded Message");
        lblEncodedMsg.setToolTipText("");

        lblEncodeKey.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblEncodeKey.setText("Key for Encoding: ");
        lblEncodeKey.setToolTipText("");

        txtAreaDecodeMsg.setColumns(20);
        txtAreaDecodeMsg.setRows(5);
        jScrollPane2.setViewportView(txtAreaDecodeMsg);

        btDecode.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        btDecode.setText("Decode Message");
        btDecode.setToolTipText("Decodes the message from the file");
        btDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecodeActionPerformed(evt);
            }
        });

        txtAreaEncodeMsg.setColumns(20);
        txtAreaEncodeMsg.setRows(5);
        jScrollPane3.setViewportView(txtAreaEncodeMsg);

        lblEncodedMsg1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblEncodedMsg1.setText("Decoded Message");
        lblEncodedMsg1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEncodedMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEncodeKey)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEncodedMsg1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(btDecode))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDecode, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncodedMsg)
                    .addComponent(lblEncodeKey))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblEncodedMsg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Decode", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // performs the encoding of the message and displays the encoded
    // message back to the user
    private void btEncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncodeActionPerformed
        String msg = txtFieldMsg.getText();
        
        if(rbRandom.isSelected())
        {
            enigma.setMessage(msg);
        }
        else
        {
            int key = (int)cbxKey.getSelectedItem();
            enigma.setMessage(msg, key);
        }
        
        txtAreaResults.setText(enigma.getEncodedMessage());
        cbxKey.setSelectedItem(enigma.getKey()); 
    }//GEN-LAST:event_btEncodeActionPerformed

    // Saves encoded message and key used to encode to a file 
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        createFilePath();
    }//GEN-LAST:event_btSaveActionPerformed

    // Opens an open file dialog to select a file
    private void btOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenFileActionPerformed
        
        // Allow user to choose a file to open
        JFileChooser chooser = new JFileChooser();
        int choice = chooser.showOpenDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION)
        {
            // get the file selected by user
            File file = chooser.getSelectedFile();
            readFile(file);
        }
        
        // Display results from file to form on decode tab
        lblEncodeKey.setText("Key for Encoding: " + encodeKey);
        txtAreaEncodeMsg.setText(encodedMsg);
    }//GEN-LAST:event_btOpenFileActionPerformed

    // Resets all components back to the original state
    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        txtAreaDecodeMsg.setText("");
        txtAreaEncodeMsg.setText("");
        txtAreaResults.setText("");
        txtFieldMsg.setText("");
        rbRandom.setSelected(false);
        cbxKey.setSelectedIndex(0);
        lblEncodeKey.setText("Key for Encoding:");
        
    }//GEN-LAST:event_btClearActionPerformed

    // Decodes the encoded message and desplays the results to user
    private void btDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecodeActionPerformed
        enigma.setEncodedMessage(encodedMsg, encodeKey);
        
        txtAreaDecodeMsg.setText(enigma.getMessage());
    }//GEN-LAST:event_btDecodeActionPerformed
   
    // opens save dialog allowing the user to select a file to save to
    private void createFilePath()
    {
        JFileChooser chooser = new JFileChooser();
        int choice = chooser.showSaveDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION)
        {
            File file = chooser.getSelectedFile();
            writeToFile(file);
        }
    }
    
    // writes the encoded message and key to file selected by user
    private void writeToFile(File file)
    {
        try
        {FileWriter fstream = new FileWriter(file);
            BufferedWriter out = new BufferedWriter(fstream);
            out.write(enigma.getEncodedMessage());
            out.write("\r\n");
            out.write(Integer.toString(enigma.getKey()));
            
            out.close(); 
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error:" + ex.getMessage());
            return;
        }
                
    }
    
    // reads the encoded message from the file selected
    private void readFile(File file)
    {
        try
        {
            Scanner input = new Scanner(file);
            encodedMsg = input.nextLine();
            encodeKey = input.nextInt();
        }
        catch(FileNotFoundException fne)
        {
            JOptionPane.showMessageDialog(null, "Error:" + fne.getMessage());
            return;
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDecode;
    private javax.swing.JButton btEncode;
    private javax.swing.JButton btOpenFile;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox cbxKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblEncodeKey;
    private javax.swing.JLabel lblEncodedMsg;
    private javax.swing.JLabel lblEncodedMsg1;
    private javax.swing.JRadioButton rbRandom;
    private javax.swing.JTextArea txtAreaDecodeMsg;
    private javax.swing.JTextArea txtAreaEncodeMsg;
    private javax.swing.JTextArea txtAreaResults;
    private javax.swing.JTextField txtFieldMsg;
    // End of variables declaration//GEN-END:variables
}
