package chavezp1;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * GUI for entering tip information and displaying calculated results to the 
 * user.
 * 
 * @author Steven Chavez <schavez256@yahoo.com>
 * File: TipsterFrame.java
 * Program 1: Java Review
 */
public class TipsterFrame extends javax.swing.JFrame {

    TipsterCalc calc;
    NumberFormat formatter = new DecimalFormat("#0.00");
    
    private double billAmount;
    private int numbPeople;
    private int tipPercent;
    /**
     * Creates new form NewJFrame
     */
    public TipsterFrame() {
        initComponents();
        
        calc = new TipsterCalc();
        
        sliderTip.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
               
               lblTipPercent.setText("Tip " + sliderTip.getValue() + "%");  
               
               if(!"".equals(txfBillAmount.getText()) || !"".equals(txfNumDiners.getText()))
                {
                    getFormInfo();
                    calc.setInputData(billAmount, numbPeople, tipPercent);
                    updateForm();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfBillAmount = new javax.swing.JTextField();
        txfNumDiners = new javax.swing.JTextField();
        lblTipPercent = new javax.swing.JLabel();
        sliderTip = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        lblTipAmount = new javax.swing.JLabel();
        lblTotalBill = new javax.swing.JLabel();
        lblEachOwes = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Tipster Tip Calculator ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Amount of Bill:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Number of People");

        lblTipPercent.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTipPercent.setText("Tip 20%");

        sliderTip.setMajorTickSpacing(10);
        sliderTip.setMaximum(50);
        sliderTip.setMinimum(20);
        sliderTip.setMinorTickSpacing(5);
        sliderTip.setPaintLabels(true);
        sliderTip.setPaintTicks(true);
        sliderTip.setToolTipText("");
        sliderTip.setValue(20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTipAmount.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTipAmount.setText("Tip Amount:");

        lblTotalBill.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTotalBill.setText("Total Due:");

        lblEachOwes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblEachOwes.setText("Total Per Person:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNumDiners, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sliderTip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblTipPercent))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalBill)
                            .addComponent(lblTipAmount)
                            .addComponent(lblEachOwes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfNumDiners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(lblTipPercent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sliderTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblTipAmount)
                .addGap(18, 18, 18)
                .addComponent(lblTotalBill)
                .addGap(18, 18, 18)
                .addComponent(lblEachOwes)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txfBillAmount.setText("");
        txfNumDiners.setText("");
        sliderTip.setValue(20);
        lblEachOwes.setText("Total Per Person:");
        lblTotalBill.setText("Total Due:");
        lblTipAmount.setText("Tip Amount:");
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getFormInfo()
    {
        billAmount = Double.parseDouble(txfBillAmount.getText());
        numbPeople = Integer.parseInt(txfNumDiners.getText());
        tipPercent = sliderTip.getValue();
    }
    
    private void updateForm()
    {
        lblTipAmount.setText("Tip Amount: $" + 
                             formatter.format(calc.getTipAmount()));
        
        lblTotalBill.setText("Total Due: $" +
                             formatter.format(calc.getBillTotal()));
        
        lblEachOwes.setText("Total Per Person: $" +
                             formatter.format(calc.getAmountEachDinerOwes()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEachOwes;
    private javax.swing.JLabel lblTipAmount;
    private javax.swing.JLabel lblTipPercent;
    private javax.swing.JLabel lblTotalBill;
    private javax.swing.JSlider sliderTip;
    private javax.swing.JTextField txfBillAmount;
    private javax.swing.JTextField txfNumDiners;
    // End of variables declaration//GEN-END:variables
}
